name:                Ottomata
version:             0.1.0.0
github:              "bivoje/Ottomata"
license:             BSD3
author:              "bivoje"
maintainer:          "bivoje49@gmail.com"
copyright:           "2021 bivoje"

dependencies:
- base >= 4.7 && < 5
- graphviz
- text
- containers
- mtl

library:
  source-dirs: .
